In [21]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
dataset =pd.read_csv('fidata.csv')

In [23]:
type(dataset)

pandas.core.frame.DataFrame

In [24]:
dataset

Item         Element    Unit        Y2014
0    Anise, badian, fennel, coriander           Yield   hg/ha     726228.0
1    Anise, badian, fennel, coriander      Production  tonnes       8042.0
2                              Apples  Area harvested      ha     584000.0
3                              Apples           Yield   hg/ha     313040.0
4                              Apples      Production  tonnes      79788.0
5                            Apricots  Area harvested      ha    2497680.0
6                            Apricots           Yield   hg/ha       5000.0
7                            Apricots      Production  tonnes      27998.0
8                          Areca nuts  Area harvested      ha      13999.0
9                          Areca nuts           Yield   hg/ha     452000.0
10                         Areca nuts      Production  tonnes      13761.0
11                            Bananas  Area harvested      ha     622000.0
12                            Bananas           Yield   hg/ha     802570.0
13                            Bananas      Production  tonnes     370367.0
14                             Barley  Area harvested      ha   29724550.0
15                             Barley           Yield   hg/ha     672000.0
16                             Barley      Production  tonnes      27232.0
17                             Barley            Seed  tonnes    1830000.0
18                  Bastfibres, other  Area harvested      ha          NaN
19                  Bastfibres, other           Yield   hg/ha      87496.0
20                  Bastfibres, other      Production  tonnes      11819.0
21                         Beans, dry  Area harvested      ha     103412.0
22                         Beans, dry           Yield   hg/ha   10000000.0
23                         Beans, dry      Production  tonnes       4110.0
24                         Beans, dry            Seed  tonnes    4110000.0
25                       Beans, green  Area harvested      ha          NaN
26                       Beans, green           Yield   hg/ha     225727.0
27                       Beans, green      Production  tonnes      28180.0
28                        Berries nes  Area harvested      ha     636103.0
29                        Berries nes           Yield   hg/ha        300.0
..                                ...             ...     ...          ...
291           Fruit excl Melons,Total      Production  tonnes     123766.0
292           Jute & Jute-like Fibres  Area harvested      ha   88475053.0
293           Jute & Jute-like Fibres           Yield   hg/ha     828496.0
294           Jute & Jute-like Fibres      Production  tonnes      25002.0
295               Oilcakes Equivalent  Area harvested      ha    2071412.0
296               Oilcakes Equivalent           Yield   hg/ha   40516740.0
297               Oilcakes Equivalent      Production  tonnes       5802.0
298               Oilcakes Equivalent            Seed  tonnes   23506770.0
299                  Oilcrops Primary  Area harvested      ha          NaN
300                  Oilcrops Primary           Yield   hg/ha   41556740.0
301                  Oilcrops Primary      Production  tonnes       2788.0
302                  Oilcrops Primary            Seed  tonnes   11586533.0
303                      Pulses,Total  Area harvested      ha          NaN
304                      Pulses,Total           Yield   hg/ha   30309000.0
305                      Pulses,Total      Production  tonnes       6592.0
306                      Pulses,Total            Seed  tonnes   19980000.0
307            Roots and Tubers,Total  Area harvested      ha          NaN
308            Roots and Tubers,Total           Yield   hg/ha    2358150.0
309            Roots and Tubers,Total      Production  tonnes     235873.0
310            Roots and Tubers,Total            Seed  tonnes   55622310.0
311                    Treenuts,Total  Area harvested      ha          NaN
312                    Treenuts,Total           Yield   hg

In [25]:
dataset.isnull().any()

Item       False
Element    False
Unit       False
Y2014       True
dtype: bool

In [26]:
dataset["Y2014"].fillna("148677", inplace = True) 
dataset

Item         Element    Unit        Y2014
0    Anise, badian, fennel, coriander           Yield   hg/ha       726228
1    Anise, badian, fennel, coriander      Production  tonnes         8042
2                              Apples  Area harvested      ha       584000
3                              Apples           Yield   hg/ha       313040
4                              Apples      Production  tonnes        79788
5                            Apricots  Area harvested      ha  2.49768e+06
6                            Apricots           Yield   hg/ha         5000
7                            Apricots      Production  tonnes        27998
8                          Areca nuts  Area harvested      ha        13999
9                          Areca nuts           Yield   hg/ha       452000
10                         Areca nuts      Production  tonnes        13761
11                            Bananas  Area harvested      ha       622000
12                            Bananas           Yield   hg/ha       802570
13                            Bananas      Production  tonnes       370367
14                             Barley  Area harvested      ha  2.97246e+07
15                             Barley           Yield   hg/ha       672000
16                             Barley      Production  tonnes        27232
17                             Barley            Seed  tonnes     1.83e+06
18                  Bastfibres, other  Area harvested      ha       148677
19                  Bastfibres, other           Yield   hg/ha        87496
20                  Bastfibres, other      Production  tonnes        11819
21                         Beans, dry  Area harvested      ha       103412
22                         Beans, dry           Yield   hg/ha        1e+07
23                         Beans, dry      Production  tonnes         4110
24                         Beans, dry            Seed  tonnes     4.11e+06
25                       Beans, green  Area harvested      ha       148677
26                       Beans, green           Yield   hg/ha       225727
27                       Beans, green      Production  tonnes        28180
28                        Berries nes  Area harvested      ha       636103
29                        Berries nes           Yield   hg/ha          300
..                                ...             ...     ...          ...
291           Fruit excl Melons,Total      Production  tonnes       123766
292           Jute & Jute-like Fibres  Area harvested      ha  8.84751e+07
293           Jute & Jute-like Fibres           Yield   hg/ha       828496
294           Jute & Jute-like Fibres      Production  tonnes        25002
295               Oilcakes Equivalent  Area harvested      ha  2.07141e+06
296               Oilcakes Equivalent           Yield   hg/ha  4.05167e+07
297               Oilcakes Equivalent      Production  tonnes         5802
298               Oilcakes Equivalent            Seed  tonnes  2.35068e+07
299                  Oilcrops Primary  Area harvested      ha       148677
300                  Oilcrops Primary           Yield   hg/ha  4.15567e+07
301                  Oilcrops Primary      Production  tonnes         2788
302                  Oilcrops Primary            Seed  tonnes  1.15865e+07
303                      Pulses,Total  Area harvested      ha       148677
304                      Pulses,Total           Yield   hg/ha   3.0309e+07
305                      Pulses,Total      Production  tonnes         6592
306                      Pulses,Total            Seed  tonnes    1.998e+07
307            Roots and Tubers,Total  Area harvested      ha       148677
308            Roots and Tubers,Total           Yield   hg/ha  2.35815e+06
309            Roots and Tubers,Total      Production  tonnes       235873
310            Roots and Tubers,Total            Seed  tonnes  5.56223e+07
311                    Treenuts,Total  Area harvested      ha       148677
312                    Treenuts,Total           Yield   hg

In [27]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,x,y=None):
        return self # not relevant here

    def transform(self,x):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = x.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,x,y=None):
        return self.fit(x,y).transform(x)
    

In [29]:
Dataset=MultiColumnLabelEncoder(columns = ['Item','Element','Unit']).fit_transform(dataset)

In [30]:
Dataset

Item  Element  Unit        Y2014
0       0        3     1       726228
1       0        1     2         8042
2       1        0     0       584000
3       1        3     1       313040
4       1        1     2        79788
5       2        0     0  2.49768e+06
6       2        3     1         5000
7       2        1     2        27998
8       3        0     0        13999
9       3        3     1       452000
10      3        1     2        13761
11      4        0     0       622000
12      4        3     1       802570
13      4        1     2       370367
14      5        0     0  2.97246e+07
15      5        3     1       672000
16      5        1     2        27232
17      5        2     2     1.83e+06
18      6        0     0       148677
19      6        3     1        87496
20      6        1     2        11819
21      7        0     0       103412
22      7        3     1        1e+07
23      7        1     2         4110
24      7        2     2     4.11e+06
25      8        0     0       148677
26      8        3     1       225727
27      8        1     2        28180
28      9        0     0       636103
29      9        3     1          300
..    ...      ...   ...          ...
291    34        1     2       123766
292    46        0     0  8.84751e+07
293    46        3     1       828496
294    46        1     2        25002
295    57        0     0  2.07141e+06
296    57        3     1  4.05167e+07
297    57        1     2         5802
298    57        2     2  2.35068e+07
299    58        0     0       148677
300    58        3     1  4.15567e+07
301    58        1     2         2788
302    58        2     2  1.15865e+07
303    75        0     0       148677
304    75        3     1   3.0309e+07
305    75        1     2         6592
306    75        2     2    1.998e+07
307    79        0     0       148677
308    79        3     1  2.35815e+06
309    79        1     2       235873
310    79        2     2  5.56223e+07
311    93        0     0       148677
312    93        3     1    1.042e+06
313    93        1     2         7639
314    94        0     0       796000
315    94        3     1   8.5137e+06
316    94        1     2       148677
317    95        0     0  1.26579e+08
318    95        3     1   8.5137e+06
319    95        1     2       148677
320     0        0     0  1.26579e+08

[321 rows x 4 columns]

In [35]:
X=Dataset.iloc[:,:3].values

In [36]:
x

array([[ 0,  3,  1],
       [ 0,  1,  2],
       [ 1,  0,  0],
       [ 1,  3,  1],
       [ 1,  1,  2],
       [ 2,  0,  0],
       [ 2,  3,  1],
       [ 2,  1,  2],
       [ 3,  0,  0],
       [ 3,  3,  1],
       [ 3,  1,  2],
       [ 4,  0,  0],
       [ 4,  3,  1],
       [ 4,  1,  2],
       [ 5,  0,  0],
       [ 5,  3,  1],
       [ 5,  1,  2],
       [ 5,  2,  2],
       [ 6,  0,  0],
       [ 6,  3,  1],
       [ 6,  1,  2],
       [ 7,  0,  0],
       [ 7,  3,  1],
       [ 7,  1,  2],
       [ 7,  2,  2],
       [ 8,  0,  0],
       [ 8,  3,  1],
       [ 8,  1,  2],
       [ 9,  0,  0],
       [ 9,  3,  1],
       [ 9,  1,  2],
       [10,  0,  0],
       [10,  3,  1],
       [10,  1,  2],
       [11,  0,  0],
       [11,  3,  1],
       [11,  1,  2],
       [12,  0,  0],
       [12,  3,  1],
       [12,  1,  2],
       [13,  0,  0],
       [13,  3,  1],
       [13,  1,  2],
       [14,  0,  0],
       [14,  3,  1],
       [14,  1,  2],
       [14,  2,  2],
       [15,  

In [37]:
y=Dataset.iloc[:,3:].values
y

array([[726228.0],
       [8042.0],
       [584000.0],
       [313040.0],
       [79788.0],
       [2497680.0],
       [5000.0],
       [27998.0],
       [13999.0],
       [452000.0],
       [13761.0],
       [622000.0],
       [802570.0],
       [370367.0],
       [29724550.0],
       [672000.0],
       [27232.0],
       [1830000.0],
       ['148677'],
       [87496.0],
       [11819.0],
       [103412.0],
       [10000000.0],
       [4110.0],
       [4110000.0],
       ['148677'],
       [225727.0],
       [28180.0],
       [636103.0],
       [300.0],
       [71479.0],
       [2144.0],
       [400140.0],
       [225901.0],
       [9039220.0],
       [34665.0],
       [153529.0],
       [532201.0],
       [1011000.0],
       [7448.0],
       [753000.0],
       [228280.0],
       [356555.0],
       [8139430.0],
       [1040000.0],
       [16663.0],
       [1733000.0],
       ['148677'],
       [433870.0],
       [197600.0],
       [8573280.0],
       [3500.0],
       [29202.0],
       

In [39]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
x_train

array([[53,  0,  0],
       [81,  3,  1],
       [73,  0,  0],
       [ 2,  0,  0],
       [10,  1,  2],
       [22,  3,  1],
       [11,  0,  0],
       [78,  2,  2],
       [80,  1,  2],
       [97,  1,  2],
       [52,  0,  0],
       [14,  1,  2],
       [40,  0,  0],
       [98,  1,  2],
       [49,  0,  0],
       [74,  0,  0],
       [87,  0,  0],
       [74,  3,  1],
       [82,  1,  2],
       [47,  3,  1],
       [88,  2,  2],
       [51,  1,  2],
       [27,  1,  2],
       [94,  0,  0],
       [75,  1,  2],
       [45,  0,  0],
       [92,  0,  0],
       [ 9,  3,  1],
       [38,  1,  2],
       [ 6,  1,  2],
       [14,  2,  2],
       [80,  0,  0],
       [97,  3,  1],
       [93,  1,  2],
       [36,  0,  0],
       [90,  3,  1],
       [ 8,  1,  2],
       [ 0,  0,  0],
       [93,  3,  1],
       [12,  0,  0],
       [19,  3,  1],
       [86,  3,  1],
       [96,  1,  2],
       [53,  1,  2],
       [50,  2,  2],
       [69,  1,  2],
       [71,  3,  1],
       [75,  

In [40]:
y_train

array([[18431330.0],
       [211000.0],
       ['148677'],
       [2497680.0],
       [225901.0],
       [1018991.0],
       [9039220.0],
       [157200000.0],
       [20659.0],
       [13871.0],
       ['148677'],
       [16663.0],
       [1252000.0],
       [140688.0],
       ['148677'],
       ['148677'],
       [1504000.0],
       [2250000.0],
       [15950.0],
       [286410.0],
       [415000.0],
       [25567.0],
       ['148677'],
       [796000.0],
       [6592.0],
       ['148677'],
       [720725.0],
       [300.0],
       [113299.0],
       [11819.0],
       [1733000.0],
       ['148677'],
       [31000.0],
       [7639.0],
       [745500.0],
       [604000.0],
       [28180.0],
       [126578659.0],
       [1042000.0],
       [532201.0],
       [9927000.0],
       [680000.0],
       [140442.0],
       [223500.0],
       [141000.0],
       [5873.0],
       [27600.0],
       [30309000.0],
       [5012000.0],
       [161201.0],
       [664910.0],
       [34665.0],
       [133

In [41]:
y_test

array([[4113.0],
       [18735910.0],
       [672000.0],
       [2113.0],
       [940000.0],
       [68564.0],
       [702598.0],
       [5820000.0],
       [37800.0],
       [119145.0],
       [71000.0],
       [49248.0],
       [6111.0],
       [148677.0],
       ['148677'],
       [1492000.0],
       [2835020.0],
       ['148677'],
       [15000.0],
       [225727.0],
       ['148677'],
       [1203570.0],
       [23670000.0],
       [828496.0],
       [133360.0],
       [4444.0],
       [98979000.0],
       [27998.0],
       [5000.0],
       [5390000.0],
       [16657.0],
       [10000000.0],
       [230000.0],
       [103412.0],
       [9953.0],
       [6346370.0],
       [802570.0],
       [118740.0],
       [51770.0],
       [8904000.0],
       [42280.0],
       [295360000.0],
       [19252.0],
       [9258000.0],
       ['148677'],
       [9872000.0],
       [600000.0],
       [411547.0],
       [544300.0],
       [711310.0],
       [8259412.0],
       [2623000.0],
       [4300

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
lr=LinearRegression()

In [44]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [45]:
y_predict=lr.predict(x_test)

In [46]:
y_predict

array([[ 9611156.60166831],
       [ 8256751.11203964],
       [ 7699088.21600835],
       [ 6912804.71976621],
       [ 7336858.42502756],
       [ 3841266.21438166],
       [10776354.00521694],
       [12543856.3676053 ],
       [11317332.78492253],
       [ 9120547.16859519],
       [ 8864285.61955698],
       [ 7894023.58591242],
       [ 8384633.01898553],
       [11205637.25915591],
       [ 8072772.57463723],
       [ 3657287.67697925],
       [ 5313094.51360099],
       [ 3350656.78130855],
       [ 3902592.3935158 ],
       [ 7883066.75341077],
       [ 4331875.64745477],
       [11133354.24752011],
       [ 9963511.61738117],
       [10213461.56050803],
       [11256006.60578839],
       [ 9979113.67647314],
       [ 8373676.18648387],
       [ 5563628.77881516],
       [ 7515109.67860593],
       [11987275.52880774],
       [11021658.72175349],
       [ 7821740.57427663],
       [11010701.88925184],
       [ 2798721.16910131],
       [ 6606173.82409551],
       [ 6110334.842

In [49]:
lr.predict(np.array([[7,1,2]]))

array([[5870259.67448585]])